import os
import time
import json
import urllib.request
import re

base_dir = r"d:\ThirdYearsInHell\miniproject\RavenX\tactical-ui\public\hardware"
db_path = r"d:\ThirdYearsInHell\miniproject\RavenX\tactical-ui\src\data\hardwareDatabase.js"

os.makedirs(base_dir, exist_ok=True)

# THE MASSIVE DATABASE DICTIONARY
raw_data = [
    # ==========================================
    # AIR ASSETS (35)
    # ==========================================
    {'id': 'f22', 'name': 'F-22 Raptor', 'class': 'Stealth Air Superiority Fighter', 'type': 'AIR', 'origin': 'USA', 'wiki_title': 'Lockheed_Martin_F-22_Raptor', 'desc': 'The preeminent fifth-generation air superiority fighter, featuring stealth, supercruise, and thrust vectoring.', 'stats': [{'label': 'SPEED', 'value': 95, 'text': 'Mach 2.25'}, {'label': 'RANGE', 'value': 80, 'text': '2,960 km'}, {'label': 'STEALTH', 'value': 100, 'text': 'VLO'}]},
    {'id': 'f35', 'name': 'F-35A Lightning II', 'class': 'Stealth Multirole Fighter', 'type': 'AIR', 'origin': 'USA', 'wiki_title': 'Lockheed_Martin_F-35_Lightning_II', 'desc': 'A family of single-seat, single-engine, all-weather stealth multirole combat aircraft.', 'stats': [{'label': 'SPEED', 'value': 80, 'text': 'Mach 1.6'}, {'label': 'RANGE', 'value': 65, 'text': '2,200 km'}, {'label': 'SENSORS', 'value': 100, 'text': 'Sensor Fusion'}]},
    {'id': 'su57', 'name': 'Sukhoi Su-57', 'class': 'Stealth Multirole Fighter', 'type': 'AIR', 'origin': 'RUSSIA', 'wiki_title': 'Sukhoi_Su-57', 'desc': 'A twin-engine stealth multirole fighter aircraft developed by Sukhoi.', 'stats': [{'label': 'SPEED', 'value': 90, 'text': 'Mach 2.0'}, {'label': 'RANGE', 'value': 85, 'text': '3,500 km'}, {'label': 'PAYLOAD', 'value': 85, 'text': '10,000 kg'}]},
    {'id': 'j20', 'name': 'Chengdu J-20', 'class': 'Stealth Fighter', 'type': 'AIR', 'origin': 'CHINA', 'wiki_title': 'Chengdu_J-20', 'desc': 'A twinjet all-weather stealth fighter aircraft developed by China.', 'stats': [{'label': 'SPEED', 'value': 88, 'text': 'Mach 2.0'}, {'label': 'RANGE', 'value': 90, 'text': '5,500 km'}, {'label': 'STEALTH', 'value': 85, 'text': 'VLO'}]},
    {'id': 'b2', 'name': 'B-2 Spirit', 'class': 'Stealth Strategic Bomber', 'type': 'AIR', 'origin': 'USA', 'wiki_title': 'Northrop_B-2_Spirit', 'desc': 'An American heavy strategic bomber, featuring low observable stealth technology.', 'stats': [{'label': 'SPEED', 'value': 50, 'text': 'Mach 0.95'}, {'label': 'RANGE', 'value': 100, 'text': '11,000 km'}, {'label': 'PAYLOAD', 'value': 95, 'text': '18,000 kg'}]},
    {'id': 'b21', 'name': 'B-21 Raider', 'class': 'Stealth Strategic Bomber', 'type': 'AIR', 'origin': 'USA', 'wiki_title': 'Northrop_Grumman_B-21_Raider', 'desc': 'An American heavy bomber under development for the USAF.', 'stats': [{'label': 'STEALTH', 'value': 100, 'text': 'Next-Gen VLO'}, {'label': 'RANGE', 'value': 95, 'text': 'Global'}, {'label': 'TECH', 'value': 100, 'text': 'Digital Engineering'}]},
    {'id': 'tu160', 'name': 'Tu-160 Blackjack', 'class': 'Strategic Bomber', 'type': 'AIR', 'origin': 'RUSSIA', 'wiki_title': 'Tupolev_Tu-160', 'desc': 'A supersonic, variable-sweep wing heavy strategic bomber.', 'stats': [{'label': 'SPEED', 'value': 90, 'text': 'Mach 2.05'}, {'label': 'RANGE', 'value': 95, 'text': '12,300 km'}, {'label': 'PAYLOAD', 'value': 100, 'text': '40,000 kg'}]},
    {'id': 'b52', 'name': 'B-52 Stratofortress', 'class': 'Strategic Bomber', 'type': 'AIR', 'origin': 'USA', 'wiki_title': 'Boeing_B-52_Stratofortress', 'desc': 'A long-range, subsonic, jet-powered strategic bomber operated by the USAF since the 1950s.', 'stats': [{'label': 'PAYLOAD', 'value': 95, 'text': '31,500 kg'}, {'label': 'RANGE', 'value': 100, 'text': '14,200 km'}, {'label': 'SPEED', 'value': 40, 'text': 'Mach 0.86'}]},
    {'id': 'f15', 'name': 'F-15E Strike Eagle', 'class': 'Strike Fighter', 'type': 'AIR', 'origin': 'USA', 'wiki_title': 'McDonnell_Douglas_F-15E_Strike_Eagle', 'desc': 'An American all-weather multirole strike fighter derived from the F-15 Eagle.', 'stats': [{'label': 'SPEED', 'value': 95, 'text': 'Mach 2.5'}, {'label': 'PAYLOAD', 'value': 90, 'text': '10,400 kg'}, {'label': 'RANGE', 'value': 85, 'text': '3,900 km'}]},
    {'id': 'f16', 'name': 'F-16 Fighting Falcon', 'class': 'Multirole Fighter', 'type': 'AIR', 'origin': 'USA', 'wiki_title': 'General_Dynamics_F-16_Fighting_Falcon', 'desc': 'A single-engine supersonic multirole fighter aircraft.', 'stats': [{'label': 'SPEED', 'value': 90, 'text': 'Mach 2.0'}, {'label': 'AGILITY', 'value': 95, 'text': '9G Capable'}, {'label': 'RELIABILITY', 'value': 100, 'text': 'Combat Proven'}]},
    {'id': 'f14', 'name': 'F-14 Tomcat', 'class': 'Fleet Defense Fighter', 'type': 'AIR', 'origin': 'USA', 'wiki_title': 'Grumman_F-14_Tomcat', 'desc': 'An American supersonic, twin-engine, two-seat, variable-sweep wing fighter.', 'stats': [{'label': 'SPEED', 'value': 95, 'text': 'Mach 2.34'}, {'label': 'RANGE', 'value': 80, 'text': '2,960 km'}, {'label': 'WEAPON', 'value': 90, 'text': 'AIM-54 Phoenix'}]},
    {'id': 'su27', 'name': 'Sukhoi Su-27', 'class': 'Air Superiority Fighter', 'type': 'AIR', 'origin': 'RUSSIA', 'wiki_title': 'Sukhoi_Su-27', 'desc': 'A Soviet-origin twin-engine supermaneuverable fighter aircraft.', 'stats': [{'label': 'SPEED', 'value': 95, 'text': 'Mach 2.35'}, {'label': 'MANEUVERABILITY', 'value': 98, 'text': 'Cobra Maneuver'}, {'label': 'RANGE', 'value': 85, 'text': '3,530 km'}]},
    {'id': 'su35', 'name': 'Sukhoi Su-35', 'class': 'Multirole Fighter', 'type': 'AIR', 'origin': 'RUSSIA', 'wiki_title': 'Sukhoi_Su-35', 'desc': 'A heavily upgraded derivative of the Su-27 air superiority fighter.', 'stats': [{'label': 'SPEED', 'value': 95, 'text': 'Mach 2.25'}, {'label': 'AGILITY', 'value': 100, 'text': 'Thrust Vectoring'}, {'label': 'SENSORS', 'value': 85, 'text': 'Irbis-E PESA'}]},
    {'id': 'mig29', 'name': 'MiG-29', 'class': 'Air Superiority Fighter', 'type': 'AIR', 'origin': 'RUSSIA', 'wiki_title': 'Mikoyan_MiG-29', 'desc': 'A twin-engine jet fighter aircraft designed in the Soviet Union.', 'stats': [{'label': 'SPEED', 'value': 95, 'text': 'Mach 2.25'}, {'label': 'AGILITY', 'value': 90, 'text': 'High'}, {'label': 'RANGE', 'value': 40, 'text': '1,430 km'}]},
    {'id': 'mig31', 'name': 'MiG-31 Foxhound', 'class': 'Interceptor', 'type': 'AIR', 'origin': 'RUSSIA', 'wiki_title': 'Mikoyan_MiG-31', 'desc': 'A supersonic interceptor aircraft developed for use by the Soviet Air Forces.', 'stats': [{'label': 'SPEED', 'value': 100, 'text': 'Mach 2.83'}, {'label': 'CEILING', 'value': 95, 'text': '82,000 ft'}, {'label': 'RADAR', 'value': 90, 'text': 'Zaslon PESA'}]},
    {'id': 'typhoon', 'name': 'Eurofighter Typhoon', 'class': 'Multirole Fighter', 'type': 'AIR', 'origin': 'EU', 'wiki_title': 'Eurofighter_Typhoon', 'desc': 'A twin-engine, canard delta wing, multirole fighter.', 'stats': [{'label': 'SPEED', 'value': 90, 'text': 'Mach 2.0'}, {'label': 'AGILITY', 'value': 95, 'text': 'High'}, {'label': 'PAYLOAD', 'value': 75, 'text': '9,000 kg'}]},
    {'id': 'rafale', 'name': 'Dassault Rafale', 'class': 'Omnirole Fighter', 'type': 'AIR', 'origin': 'FRANCE', 'wiki_title': 'Dassault_Rafale', 'desc': 'A French twin-engine, canard delta wing, multirole fighter.', 'stats': [{'label': 'SPEED', 'value': 85, 'text': 'Mach 1.8'}, {'label': 'VERSATILITY', 'value': 95, 'text': 'Omnirole'}, {'label': 'SENSORS', 'value': 90, 'text': 'RBE2 AESA'}]},
    {'id': 'gripen', 'name': 'JAS 39 Gripen', 'class': 'Light Multirole Fighter', 'type': 'AIR', 'origin': 'SWEDEN', 'wiki_title': 'Saab_JAS_39_Gripen', 'desc': 'A light single-engine multirole fighter aircraft manufactured by Saab.', 'stats': [{'label': 'SPEED', 'value': 90, 'text': 'Mach 2.0'}, {'label': 'COST', 'value': 95, 'text': 'Low Maintenance'}, {'label': 'AGILITY', 'value': 90, 'text': 'Canard Delta'}]},
    {'id': 'a10', 'name': 'A-10 Thunderbolt II', 'class': 'Close Air Support', 'type': 'AIR', 'origin': 'USA', 'wiki_title': 'Fairchild_Republic_A-10_Thunderbolt_II', 'desc': 'A single-seat, twin-turbofan, straight-wing, subsonic attack aircraft (The Warthog).', 'stats': [{'label': 'FIREPOWER', 'value': 100, 'text': 'GAU-8/A Avenger'}, {'label': 'SURVIVABILITY', 'value': 95, 'text': 'Titanium Armor'}, {'label': 'SPEED', 'value': 30, 'text': '706 km/h'}]},
    {'id': 'ac130', 'name': 'AC-130 Ghostrider', 'class': 'Gunship', 'type': 'AIR', 'origin': 'USA', 'wiki_title': 'Lockheed_AC-130', 'desc': 'A heavily armed, long-endurance, ground-attack variant of the C-130 Hercules transport.', 'stats': [{'label': 'FIREPOWER', 'value': 100, 'text': '105mm / 30mm'}, {'label': 'LOITER TIME', 'value': 90, 'text': 'Extended'}, {'label': 'SPEED', 'value': 20, 'text': '480 km/h'}]},
    {'id': 'apache', 'name': 'AH-64 Apache', 'class': 'Attack Helicopter', 'type': 'AIR', 'origin': 'USA', 'wiki_title': 'Boeing_AH-64_Apache', 'desc': 'An American twin-turboshaft attack helicopter.', 'stats': [{'label': 'FIREPOWER', 'value': 90, 'text': 'Hellfire/30mm'}, {'label': 'SURVIVABILITY', 'value': 80, 'text': 'Armored'}, {'label': 'SPEED', 'value': 35, 'text': '293 km/h'}]},
    {'id': 'hind', 'name': 'Mi-24 Hind', 'class': 'Attack Helicopter / Transport', 'type': 'AIR', 'origin': 'RUSSIA', 'wiki_title': 'Mil_Mi-24', 'desc': 'A large helicopter gunship, attack helicopter and low-capacity troop transport.', 'stats': [{'label': 'FIREPOWER', 'value': 85, 'text': 'Rockets/Guns'}, {'label': 'CAPACITY', 'value': 80, 'text': '8 Troops'}, {'label': 'SURVIVABILITY', 'value': 90, 'text': 'Flying Tank'}]},
    {'id': 'blackhawk', 'name': 'UH-60 Black Hawk', 'class': 'Utility Helicopter', 'type': 'AIR', 'origin': 'USA', 'wiki_title': 'Sikorsky_UH-60_Black_Hawk', 'desc': 'A four-blade, twin-engine, medium-lift utility helicopter.', 'stats': [{'label': 'SPEED', 'value': 35, 'text': '294 km/h'}, {'label': 'CAPACITY', 'value': 85, 'text': '11 Troops'}, {'label': 'VERSATILITY', 'value': 95, 'text': 'Extreme'}]},
    {'id': 'chinook', 'name': 'CH-47 Chinook', 'class': 'Heavy Lift Helicopter', 'type': 'AIR', 'origin': 'USA', 'wiki_title': 'Boeing_CH-47_Chinook', 'desc': 'A tandem rotor, heavy-lift helicopter.', 'stats': [{'label': 'PAYLOAD', 'value': 95, 'text': '10,886 kg'}, {'label': 'SPEED', 'value': 40, 'text': '315 km/h'}, {'label': 'CAPACITY', 'value': 95, 'text': '33-55 Troops'}]},
    {'id': 'osprey', 'name': 'V-22 Osprey', 'class': 'Tiltrotor Transport', 'type': 'AIR', 'origin': 'USA', 'wiki_title': 'Bell_Boeing_V-22_Osprey', 'desc': 'An American multi-mission, tiltrotor military aircraft with both VTOL and STOL capabilities.', 'stats': [{'label': 'SPEED', 'value': 60, 'text': '509 km/h'}, {'label': 'RANGE', 'value': 75, 'text': '1,627 km'}, {'label': 'CAPACITY', 'value': 85, 'text': '24 Troops'}]},
    {'id': 'mq9', 'name': 'MQ-9 Reaper', 'class': 'UCAV', 'type': 'AIR', 'origin': 'USA', 'wiki_title': 'General_Atomics_MQ-9_Reaper', 'desc': 'An unmanned aerial vehicle capable of remotely controlled or autonomous flight operations.', 'stats': [{'label': 'ENDURANCE', 'value': 90, 'text': '27 Hours'}, {'label': 'PAYLOAD', 'value': 40, 'text': '1,700 kg'}, {'label': 'SPEED', 'value': 30, 'text': '482 km/h'}]},
    {'id': 'tb2', 'name': 'Bayraktar TB2', 'class': 'UCAV', 'type': 'AIR', 'origin': 'TURKEY', 'wiki_title': 'Bayraktar_TB2', 'desc': 'A Turkish medium-altitude long-endurance unmanned combat aerial vehicle.', 'stats': [{'label': 'ENDURANCE', 'value': 85, 'text': '27 Hours'}, {'label': 'LETHALITY', 'value': 75, 'text': 'MAM-L'}, {'label': 'COST', 'value': 100, 'text': 'Low / Expendable'}]},
    {'id': 'globalhawk', 'name': 'RQ-4 Global Hawk', 'class': 'Surveillance UAV', 'type': 'AIR', 'origin': 'USA', 'wiki_title': 'Northrop_Grumman_RQ-4_Global_Hawk', 'desc': 'A high-altitude, remotely-piloted surveillance aircraft.', 'stats': [{'label': 'ENDURANCE', 'value': 100, 'text': '32+ Hours'}, {'label': 'SENSORS', 'value': 100, 'text': 'SAR / EO / IR'}, {'label': 'CEILING', 'value': 90, 'text': '60,000 ft'}]},

    # ==========================================
    # LAND ASSETS (20)
    # ==========================================
    {'id': 'm1a2', 'name': 'M1A2 Abrams', 'class': 'Main Battle Tank', 'type': 'LAND', 'origin': 'USA', 'wiki_title': 'M1_Abrams', 'desc': 'A highly mobile, heavily armored, third-generation main battle tank.', 'stats': [{'label': 'ARMOR', 'value': 95, 'text': 'Chobham/DU'}, {'label': 'FIREPOWER', 'value': 90, 'text': '120mm Smoothbore'}]},
    {'id': 'leopard2', 'name': 'Leopard 2A7', 'class': 'Main Battle Tank', 'type': 'LAND', 'origin': 'GERMANY', 'wiki_title': 'Leopard_2', 'desc': 'A German main battle tank, known for its highly effective 120mm gun.', 'stats': [{'label': 'ARMOR', 'value': 92, 'text': 'Composite'}, {'label': 'FIREPOWER', 'value': 95, 'text': '120mm L/55'}]},
    {'id': 't14', 'name': 'T-14 Armata', 'class': 'Main Battle Tank', 'type': 'LAND', 'origin': 'RUSSIA', 'wiki_title': 'T-14_Armata', 'desc': 'A next-generation Russian tank with an unmanned turret.', 'stats': [{'label': 'ARMOR', 'value': 90, 'text': 'Malachit ERA'}, {'label': 'SURVIVABILITY', 'value': 95, 'text': 'Crew Capsule'}]},
    {'id': 't90', 'name': 'T-90M Proryv', 'class': 'Main Battle Tank', 'type': 'LAND', 'origin': 'RUSSIA', 'wiki_title': 'T-90', 'desc': 'A third-generation Russian main battle tank.', 'stats': [{'label': 'ARMOR', 'value': 85, 'text': 'Relikt ERA'}, {'label': 'FIREPOWER', 'value': 85, 'text': '125mm Smoothbore'}]},
    {'id': 't72', 'name': 'T-72', 'class': 'Main Battle Tank', 'type': 'LAND', 'origin': 'RUSSIA', 'wiki_title': 'T-72', 'desc': 'A family of Soviet main battle tanks that entered production in 1971.', 'stats': [{'label': 'ARMOR', 'value': 60, 'text': 'ERA capable'}, {'label': 'PRODUCTION', 'value': 100, 'text': 'Mass Produced'}]},
    {'id': 'k2', 'name': 'K2 Black Panther', 'class': 'Main Battle Tank', 'type': 'LAND', 'origin': 'SOUTH KOREA', 'wiki_title': 'K2_Black_Panther', 'desc': 'A next-generation South Korean main battle tank.', 'stats': [{'label': 'ARMOR', 'value': 88, 'text': 'Classified Composite'}, {'label': 'TECH', 'value': 95, 'text': 'Auto-target'}]},
    {'id': 'challenger2', 'name': 'Challenger 2', 'class': 'Main Battle Tank', 'type': 'LAND', 'origin': 'UK', 'wiki_title': 'Challenger_2', 'desc': 'A British main battle tank renowned for its impenetrable Dorchester armor.', 'stats': [{'label': 'ARMOR', 'value': 100, 'text': 'Dorchester Lvl 2'}, {'label': 'FIREPOWER', 'value': 85, 'text': '120mm Rifled'}]},
    {'id': 'bradley', 'name': 'M2 Bradley', 'class': 'Infantry Fighting Vehicle', 'type': 'LAND', 'origin': 'USA', 'wiki_title': 'Bradley_Fighting_Vehicle', 'desc': 'An American infantry fighting vehicle designed to transport infantry with armor protection.', 'stats': [{'label': 'FIREPOWER', 'value': 80, 'text': '25mm + TOW'}, {'label': 'CAPACITY', 'value': 70, 'text': '6 Infantry'}]},
    {'id': 'marder', 'name': 'Marder 1A3', 'class': 'Infantry Fighting Vehicle', 'type': 'LAND', 'origin': 'GERMANY', 'wiki_title': 'Marder_(infantry_fighting_vehicle)', 'desc': 'A German infantry fighting vehicle operated by the German Army.', 'stats': [{'label': 'FIREPOWER', 'value': 75, 'text': '20mm Autocannon'}, {'label': 'ARMOR', 'value': 75, 'text': 'Steel'}]},
    {'id': 'puma', 'name': 'Puma IFV', 'class': 'Infantry Fighting Vehicle', 'type': 'LAND', 'origin': 'GERMANY', 'wiki_title': 'Puma_(infantry_fighting_vehicle)', 'desc': 'One of the world\'s best-protected infantry fighting vehicles.', 'stats': [{'label': 'ARMOR', 'value': 95, 'text': 'Modular Composite'}, {'label': 'FIREPOWER', 'value': 85, 'text': '30mm ABM'}]},
    {'id': 'bmp3', 'name': 'BMP-3', 'class': 'Infantry Fighting Vehicle', 'type': 'LAND', 'origin': 'RUSSIA', 'wiki_title': 'BMP-3', 'desc': 'A Russian IFV featuring an exceptionally heavy armament.', 'stats': [{'label': 'FIREPOWER', 'value': 90, 'text': '100mm + 30mm'}, {'label': 'MOBILITY', 'value': 75, 'text': 'Amphibious'}]},
    {'id': 'btr80', 'name': 'BTR-80', 'class': 'Armored Personnel Carrier', 'type': 'LAND', 'origin': 'RUSSIA', 'wiki_title': 'BTR-80', 'desc': 'An 8x8 wheeled amphibious armored personnel carrier.', 'stats': [{'label': 'MOBILITY', 'value': 85, 'text': 'Wheeled'}, {'label': 'CAPACITY', 'value': 80, 'text': '7 Infantry'}]},
    {'id': 'stryker', 'name': 'Stryker ICV', 'class': 'Armored Combat Vehicle', 'type': 'LAND', 'origin': 'USA', 'wiki_title': 'Stryker', 'desc': 'An eight-wheeled armored fighting vehicle.', 'stats': [{'label': 'MOBILITY', 'value': 95, 'text': '97 km/h'}, {'label': 'VERSATILITY', 'value': 90, 'text': 'Multi-variant'}]},
    {'id': 'm113', 'name': 'M113', 'class': 'Armored Personnel Carrier', 'type': 'LAND', 'origin': 'USA', 'wiki_title': 'M113_armored_personnel_carrier', 'desc': 'A fully tracked armored personnel carrier that forms the backbone of mechanized infantry globally.', 'stats': [{'label': 'PRODUCTION', 'value': 100, 'text': '80,000+ Built'}, {'label': 'ARMOR', 'value': 30, 'text': 'Aluminum'}]},
    {'id': 'himars', 'name': 'M142 HIMARS', 'class': 'Multiple Rocket Launcher', 'type': 'LAND', 'origin': 'USA', 'wiki_title': 'M142_HIMARS', 'desc': 'A highly mobile artillery rocket system.', 'stats': [{'label': 'RANGE', 'value': 85, 'text': '300+ km (ATACMS)'}, {'label': 'ACCURACY', 'value': 95, 'text': 'GPS Guided'}]},
    {'id': 'm270', 'name': 'M270 MLRS', 'class': 'Multiple Rocket Launcher', 'type': 'LAND', 'origin': 'USA', 'wiki_title': 'M270_Multiple_Launch_Rocket_System', 'desc': 'An armored, self-propelled, multiple rocket launcher.', 'stats': [{'label': 'FIREPOWER', 'value': 100, 'text': '12x 227mm'}, {'label': 'MOBILITY', 'value': 50, 'text': 'Tracked'}]},
    {'id': 'tos1a', 'name': 'TOS-1A', 'class': 'Heavy Flamethrower System', 'type': 'LAND', 'origin': 'RUSSIA', 'wiki_title': 'TOS-1', 'desc': 'A Russian 220mm multiple rocket launcher and thermobaric weapon.', 'stats': [{'label': 'LETHALITY', 'value': 100, 'text': 'Thermobaric'}, {'label': 'RANGE', 'value': 20, 'text': '6 km'}]},
    {'id': 'paladin', 'name': 'M109A7 Paladin', 'class': 'Self-Propelled Howitzer', 'type': 'LAND', 'origin': 'USA', 'wiki_title': 'M109_howitzer', 'desc': 'An American 155 mm turreted self-propelled howitzer.', 'stats': [{'label': 'RANGE', 'value': 60, 'text': '30 km'}, {'label': 'FIRE RATE', 'value': 50, 'text': '4 rds/min'}]},
    {'id': 'pzh2000', 'name': 'Panzerhaubitze 2000', 'class': 'Self-Propelled Howitzer', 'type': 'LAND', 'origin': 'GERMANY', 'wiki_title': 'Panzerhaubitze_2000', 'desc': 'A German 155 mm self-propelled howitzer developed by Krauss-Maffei Wegmann.', 'stats': [{'label': 'FIRE RATE', 'value': 90, 'text': '10 rds/min'}, {'label': 'RANGE', 'value': 70, 'text': '40+ km'}]},
    {'id': 'caesar', 'name': 'CAESAR', 'class': 'Self-Propelled Howitzer', 'type': 'LAND', 'origin': 'FRANCE', 'wiki_title': 'CAESAR_self-propelled_howitzer', 'desc': 'A French 155 mm, 52-caliber self-propelled howitzer installed on a 6x6 truck chassis.', 'stats': [{'label': 'MOBILITY', 'value': 95, 'text': 'Wheeled (100 km/h)'}, {'label': 'RANGE', 'value': 70, 'text': '40+ km'}]},

    # ==========================================
    # NAVAL ASSETS (20)
    # ==========================================
    {'id': 'ford', 'name': 'Gerald R. Ford-class', 'class': 'Nuclear Aircraft Carrier', 'type': 'NAVAL', 'origin': 'USA', 'wiki_title': 'Gerald_R._Ford-class_aircraft_carrier', 'desc': 'The newest class of supercarriers for the US Navy.', 'stats': [{'label': 'DISPLACEMENT', 'value': 100, 'text': '100,000+ tons'}, {'label': 'CAPACITY', 'value': 95, 'text': '75+ Aircraft'}]},
    {'id': 'nimitz', 'name': 'Nimitz-class Carrier', 'class': 'Nuclear Aircraft Carrier', 'type': 'NAVAL', 'origin': 'USA', 'wiki_title': 'Nimitz-class_aircraft_carrier', 'desc': 'A class of ten nuclear-powered aircraft carriers.', 'stats': [{'label': 'CAPACITY', 'value': 95, 'text': '85-90 Aircraft'}, {'label': 'RANGE', 'value': 100, 'text': 'Unlimited'}]},
    {'id': 'queenelizabeth', 'name': 'Queen Elizabeth-class', 'class': 'Aircraft Carrier', 'type': 'NAVAL', 'origin': 'UK', 'wiki_title': 'Queen_Elizabeth-class_aircraft_carrier', 'desc': 'A class of two aircraft carriers of the Royal Navy.', 'stats': [{'label': 'DISPLACEMENT', 'value': 70, 'text': '65,000 tons'}, {'label': 'CAPACITY', 'value': 80, 'text': '65 Aircraft'}]},
    {'id': 'arleigh', 'name': 'Arleigh Burke-class', 'class': 'Guided Missile Destroyer', 'type': 'NAVAL', 'origin': 'USA', 'wiki_title': 'Arleigh_Burke-class_destroyer', 'desc': 'The backbone of the US Navy surface fleet, equipped with the Aegis System.', 'stats': [{'label': 'VLS CELLS', 'value': 90, 'text': '90-96 Cells'}, {'label': 'RADAR', 'value': 95, 'text': 'Aegis / SPY-1D'}]},
    {'id': 'type055', 'name': 'Type 055 Destroyer', 'class': 'Guided Missile Destroyer', 'type': 'NAVAL', 'origin': 'CHINA', 'wiki_title': 'Type_055_destroyer', 'desc': 'A class of stealth guided missile destroyers for the Chinese Navy.', 'stats': [{'label': 'VLS CELLS', 'value': 95, 'text': '112 Cells'}, {'label': 'SENSORS', 'value': 90, 'text': 'Dual-band Radar'}]},
    {'id': 'zumwalt', 'name': 'Zumwalt-class', 'class': 'Guided Missile Destroyer', 'type': 'NAVAL', 'origin': 'USA', 'wiki_title': 'Zumwalt-class_destroyer', 'desc': 'A class of three United States Navy guided-missile destroyers designed as stealth ships.', 'stats': [{'label': 'STEALTH', 'value': 100, 'text': 'Ultra-low RCS'}, {'label': 'VLS CELLS', 'value': 85, 'text': '80 Mk 57'}]},
    {'id': 'kirov', 'name': 'Kirov-class', 'class': 'Nuclear Battlecruiser', 'type': 'NAVAL', 'origin': 'RUSSIA', 'wiki_title': 'Kirov-class_battlecruiser', 'desc': 'A class of nuclear-powered military ships of the Russian Navy, the largest surface combatants.', 'stats': [{'label': 'DISPLACEMENT', 'value': 95, 'text': '28,000 tons'}, {'label': 'FIREPOWER', 'value': 100, 'text': 'Massive VLS / Missiles'}]},
    {'id': 'slava', 'name': 'Slava-class', 'class': 'Guided Missile Cruiser', 'type': 'NAVAL', 'origin': 'RUSSIA', 'wiki_title': 'Slava-class_cruiser', 'desc': 'A class of large, conventionally powered warships of the Russian Navy.', 'stats': [{'label': 'ANTI-SHIP', 'value': 95, 'text': '16 P-500/P-1000'}, {'label': 'DISPLACEMENT', 'value': 60, 'text': '11,490 tons'}]},
    {'id': 'ticonderoga', 'name': 'Ticonderoga-class', 'class': 'Guided Missile Cruiser', 'type': 'NAVAL', 'origin': 'USA', 'wiki_title': 'Ticonderoga-class_cruiser', 'desc': 'A class of guided-missile cruisers operated by the United States Navy.', 'stats': [{'label': 'VLS CELLS', 'value': 100, 'text': '122 Cells'}, {'label': 'RADAR', 'value': 95, 'text': 'Aegis'}]},
    {'id': 'virginia', 'name': 'Virginia-class', 'class': 'Nuclear Attack Submarine', 'type': 'NAVAL', 'origin': 'USA', 'wiki_title': 'Virginia-class_submarine', 'desc': 'The US Navy\'s latest class of nuclear-powered fast attack submarines.', 'stats': [{'label': 'STEALTH', 'value': 100, 'text': 'Ultra-Quiet'}, {'label': 'SPECIAL OPS', 'value': 90, 'text': 'SEAL Delivery'}]},
    {'id': 'losangeles', 'name': 'Los Angeles-class', 'class': 'Nuclear Attack Submarine', 'type': 'NAVAL', 'origin': 'USA', 'wiki_title': 'Los_Angeles-class_submarine', 'desc': 'A class of nuclear-powered fast attack submarines that forms the backbone of the US Navy submarine force.', 'stats': [{'label': 'STEALTH', 'value': 80, 'text': 'Quiet'}, {'label': 'SPEED', 'value': 85, 'text': '33+ knots'}]},
    {'id': 'yasen', 'name': 'Yasen-M Class', 'class': 'Nuclear Cruise Missile Submarine', 'type': 'NAVAL', 'origin': 'RUSSIA', 'wiki_title': 'Yasen-class_submarine', 'desc': 'The newest class of Russian nuclear-powered cruise missile submarines.', 'stats': [{'label': 'STEALTH', 'value': 95, 'text': 'Ultra-Quiet'}, {'label': 'FIREPOWER', 'value': 90, 'text': 'Zircon/Kalibr'}]},
    {'id': 'akula', 'name': 'Akula-class', 'class': 'Nuclear Attack Submarine', 'type': 'NAVAL', 'origin': 'RUSSIA', 'wiki_title': 'Akula-class_submarine', 'desc': 'A series of nuclear-powered attack submarines first deployed by the Soviet Navy.', 'stats': [{'label': 'STEALTH', 'value': 85, 'text': 'Very Quiet'}, {'label': 'DEPTH', 'value': 85, 'text': '600 meters'}]},
    {'id': 'kilo', 'name': 'Kilo-class', 'class': 'Diesel-Electric Attack Submarine', 'type': 'NAVAL', 'origin': 'RUSSIA', 'wiki_title': 'Kilo-class_submarine', 'desc': 'A class of diesel-electric attack submarines designed in the Soviet Union. Known as the "Black Hole".', 'stats': [{'label': 'STEALTH', 'value': 95, 'text': 'Extremely Quiet (Battery)'}, {'label': 'ENDURANCE', 'value': 40, 'text': '45 Days'}]},
    {'id': 'ohio', 'name': 'Ohio-class', 'class': 'Ballistic Missile Submarine', 'type': 'NAVAL', 'origin': 'USA', 'wiki_title': 'Ohio-class_submarine', 'desc': 'The sea-based leg of the US nuclear triad.', 'stats': [{'label': 'STRATEGIC', 'value': 100, 'text': 'Nuclear Deterrence'}, {'label': 'PAYLOAD', 'value': 100, 'text': '20 Trident II D5'}]},
    {'id': 'borei', 'name': 'Borei-class', 'class': 'Ballistic Missile Submarine', 'type': 'NAVAL', 'origin': 'RUSSIA', 'wiki_title': 'Borei-class_submarine', 'desc': 'The backbone of the Russian Navy\'s strategic nuclear deterrent.', 'stats': [{'label': 'STRATEGIC', 'value': 100, 'text': 'Nuclear Deterrence'}, {'label': 'PAYLOAD', 'value': 95, 'text': '16 RSM-56 Bulava'}]},
    {'id': 'astute', 'name': 'Astute-class', 'class': 'Nuclear Attack Submarine', 'type': 'NAVAL', 'origin': 'UK', 'wiki_title': 'Astute-class_submarine', 'desc': 'The most advanced attack submarines operated by the Royal Navy.', 'stats': [{'label': 'STEALTH', 'value': 95, 'text': 'Anechoic Tiles'}, {'label': 'SENSORS', 'value': 95, 'text': 'Sonar 2076'}]},
    {'id': 'mistral', 'name': 'Mistral-class', 'class': 'Amphibious Assault Ship', 'type': 'NAVAL', 'origin': 'FRANCE', 'wiki_title': 'Mistral-class_amphibious_assault_ship', 'desc': 'A class of three amphibious assault ships, also known as helicopter carriers.', 'stats': [{'label': 'CAPACITY', 'value': 90, 'text': '16 Helicopters'}, {'label': 'TROOPS', 'value': 85, 'text': '900 Marines'}]},
    {'id': 'lcs', 'name': 'Littoral Combat Ship', 'class': 'Surface Combatant', 'type': 'NAVAL', 'origin': 'USA', 'wiki_title': 'Littoral_combat_ship', 'desc': 'Small surface vessels designed for operations near shore.', 'stats': [{'label': 'SPEED', 'value': 95, 'text': '40+ knots'}, {'label': 'DRAFT', 'value': 90, 'text': 'Shallow / Littoral'}]},

    # ==========================================
    # WEAPONS / GUNS / AIR DEFENSE (50)
    # ==========================================
    {'id': 'patriot', 'name': 'MIM-104 Patriot', 'class': 'Air Defense System', 'type': 'WEAPONS', 'origin': 'USA', 'wiki_title': 'MIM-104_Patriot', 'desc': 'A primary surface-to-air missile system used by the US Army.', 'stats': [{'label': 'ENGAGE RANGE', 'value': 80, 'text': '160 km'}, {'label': 'INTERCEPT', 'value': 85, 'text': 'Hit-to-Kill'}]},
    {'id': 's400', 'name': 'S-400 Triumf', 'class': 'Mobile Air Defense System', 'type': 'WEAPONS', 'origin': 'RUSSIA', 'wiki_title': 'S-400_missile_system', 'desc': 'A mobile, surface-to-air missile system.', 'stats': [{'label': 'ENGAGE RANGE', 'value': 95, 'text': '400 km'}, {'label': 'TARGETS', 'value': 90, 'text': '80 simultaneous'}]},
    {'id': 'thaad', 'name': 'THAAD System', 'class': 'Anti-Ballistic Missile Defense', 'type': 'WEAPONS', 'origin': 'USA', 'wiki_title': 'Terminal_High_Altitude_Area_Defense', 'desc': 'Designed to shoot down short, medium, and intermediate-range ballistic missiles.', 'stats': [{'label': 'INTERCEPT', 'value': 100, 'text': 'Hit-to-Kill'}, {'label': 'RADAR', 'value': 100, 'text': 'AN/TPY-2'}]},
    {'id': 'irondome', 'name': 'Iron Dome', 'class': 'C-RAM / Air Defense System', 'type': 'WEAPONS', 'origin': 'ISRAEL', 'wiki_title': 'Iron_Dome', 'desc': 'A mobile all-weather air defense system designed to intercept rockets.', 'stats': [{'label': 'INTERCEPT RATE', 'value': 90, 'text': '~90% Effectiveness'}, {'label': 'RANGE', 'value': 50, 'text': '4-70 km'}]},
    {'id': 's300', 'name': 'S-300', 'class': 'Surface-to-Air Missile System', 'type': 'WEAPONS', 'origin': 'RUSSIA', 'wiki_title': 'S-300_missile_system', 'desc': 'A family of Russian long-range surface-to-air missile systems.', 'stats': [{'label': 'RANGE', 'value': 85, 'text': '150-200 km'}, {'label': 'PRODUCTION', 'value': 95, 'text': 'Widely Exported'}]},
    {'id': 'pantsir', 'name': 'Pantsir-S1', 'class': 'Self-Propelled Anti-Aircraft', 'type': 'WEAPONS', 'origin': 'RUSSIA', 'wiki_title': 'Pantsir_missile_system', 'desc': 'A family of self-propelled, medium-range surface-to-air missile and anti-aircraft artillery systems.', 'stats': [{'label': 'FIREPOWER', 'value': 90, 'text': 'Guns + Missiles'}, {'label': 'MOBILITY', 'value': 90, 'text': 'Wheeled Chassis'}]},
    {'id': 'kinzhal', 'name': 'Kh-47M2 Kinzhal', 'class': 'Hypersonic Aero-Ballistic Missile', 'type': 'WEAPONS', 'origin': 'RUSSIA', 'wiki_title': 'Kh-47M2_Kinzhal', 'desc': 'A Russian nuclear-capable hypersonic aero-ballistic air-to-surface missile.', 'stats': [{'label': 'SPEED', 'value': 100, 'text': 'Mach 10+'}, {'label': 'RANGE', 'value': 85, 'text': '2,000 km'}]},
    {'id': 'atacms', 'name': 'MGM-140 ATACMS', 'class': 'Tactical Ballistic Missile', 'type': 'WEAPONS', 'origin': 'USA', 'wiki_title': 'MGM-140_ATACMS', 'desc': 'A surface-to-surface missile manufactured by Lockheed Martin.', 'stats': [{'label': 'RANGE', 'value': 80, 'text': '300 km'}, {'label': 'SPEED', 'value': 85, 'text': 'Mach 3+'}]},
    {'id': 'javelin', 'name': 'FGM-148 Javelin', 'class': 'Anti-Tank Guided Missile', 'type': 'WEAPONS', 'origin': 'USA', 'wiki_title': 'FGM-148_Javelin', 'desc': 'An American man-portable fire-and-forget anti-tank missile.', 'stats': [{'label': 'RANGE', 'value': 40, 'text': '4,000 m'}, {'label': 'LETHALITY', 'value': 95, 'text': 'Tandem HEAT'}]},
    {'id': 'nlaw', 'name': 'NLAW (MBT LAW)', 'class': 'Anti-Tank Guided Missile', 'type': 'WEAPONS', 'origin': 'SWEDEN/UK', 'wiki_title': 'NLAW', 'desc': 'A joint Swedish and British short-range fire-and-forget anti-tank missile system.', 'stats': [{'label': 'RANGE', 'value': 20, 'text': '800 m'}, {'label': 'LETHALITY', 'value': 90, 'text': 'Top-Attack HEAT'}]},
    {'id': 'm777', 'name': 'M777 Howitzer', 'class': 'Towed 155mm Artillery', 'type': 'WEAPONS', 'origin': 'UK/USA', 'wiki_title': 'M777_howitzer', 'desc': 'A lightweight 155mm towed howitzer.', 'stats': [{'label': 'RANGE', 'value': 60, 'text': '30-40 km'}, {'label': 'WEIGHT', 'value': 100, 'text': '4,200 kg'}]},
    
    # SMALL ARMS
    {'id': 'm4a1', 'name': 'M4A1 Carbine', 'class': 'Assault Rifle', 'type': 'WEAPONS', 'origin': 'USA', 'wiki_title': 'M4_carbine', 'desc': 'The standard issue infantry weapon for the US military.', 'stats': [{'label': 'CALIBER', 'value': 50, 'text': '5.56x45mm NATO'}, {'label': 'FIRE RATE', 'value': 80, 'text': '700-950 RPM'}]},
    {'id': 'm16', 'name': 'M16 Rifle', 'class': 'Assault Rifle', 'type': 'WEAPONS', 'origin': 'USA', 'wiki_title': 'M16_rifle', 'desc': 'A family of military rifles adapted from the ArmaLite AR-15.', 'stats': [{'label': 'CALIBER', 'value': 50, 'text': '5.56x45mm NATO'}, {'label': 'RANGE', 'value': 70, 'text': '600 m'}]},
    {'id': 'ak47', 'name': 'AK-47', 'class': 'Assault Rifle', 'type': 'WEAPONS', 'origin': 'USSR', 'wiki_title': 'AK-47', 'desc': 'A gas-operated assault rifle that is the most widely used shoulder weapon in the world.', 'stats': [{'label': 'CALIBER', 'value': 70, 'text': '7.62x39mm'}, {'label': 'RELIABILITY', 'value': 100, 'text': 'Legendary'}]},
    {'id': 'ak74m', 'name': 'AK-74M', 'class': 'Assault Rifle', 'type': 'WEAPONS', 'origin': 'RUSSIA', 'wiki_title': 'AK-74', 'desc': 'The modernized main service rifle of the Russian Armed Forces.', 'stats': [{'label': 'CALIBER', 'value': 60, 'text': '5.45x39mm'}, {'label': 'RANGE', 'value': 60, 'text': '500 m'}]},
    {'id': 'ak12', 'name': 'AK-12', 'class': 'Assault Rifle', 'type': 'WEAPONS', 'origin': 'RUSSIA', 'wiki_title': 'AK-12', 'desc': 'The newest derivative of the Soviet/Russian AK-pattern series.', 'stats': [{'label': 'CALIBER', 'value': 60, 'text': '5.45x39mm'}, {'label': 'ERGONOMICS', 'value': 85, 'text': 'Modernized'}]},
    {'id': 'hk416', 'name': 'Heckler & Koch HK416', 'class': 'Assault Rifle', 'type': 'WEAPONS', 'origin': 'GERMANY', 'wiki_title': 'Heckler_%_%26_Koch_HK416', 'desc': 'A gas-piston assault rifle used by special forces globally, including JSOC.', 'stats': [{'label': 'CALIBER', 'value': 50, 'text': '5.56x45mm NATO'}, {'label': 'RELIABILITY', 'value': 95, 'text': 'Short-stroke piston'}]},
    {'id': 'scar', 'name': 'FN SCAR-H', 'class': 'Battle Rifle', 'type': 'WEAPONS', 'origin': 'BELGIUM', 'wiki_title': 'FN_SCAR', 'desc': 'The Special Operations Forces Combat Assault Rifle.', 'stats': [{'label': 'CALIBER', 'value': 80, 'text': '7.62x51mm NATO'}, {'label': 'STOPPING POWER', 'value': 90, 'text': 'High'}]},
    {'id': 'g36', 'name': 'Heckler & Koch G36', 'class': 'Assault Rifle', 'type': 'WEAPONS', 'origin': 'GERMANY', 'wiki_title': 'Heckler_%_%26_Koch_G36', 'desc': 'A 5.56x45mm assault rifle designed in the early 1990s as a replacement for the G3.', 'stats': [{'label': 'CALIBER', 'value': 50, 'text': '5.56x45mm NATO'}, {'label': 'WEIGHT', 'value': 85, 'text': 'Polymer Body'}]},
    {'id': 'famas', 'name': 'FAMAS', 'class': 'Assault Rifle (Bullpup)', 'type': 'WEAPONS', 'origin': 'FRANCE', 'wiki_title': 'FAMAS', 'desc': 'A bullpup assault rifle designed and manufactured in France. Known as "The Bugle".', 'stats': [{'label': 'FIRE RATE', 'value': 85, 'text': '900-1000 RPM'}, {'label': 'COMPACTNESS', 'value': 90, 'text': 'Bullpup Design'}]},
    {'id': 'aug', 'name': 'Steyr AUG', 'class': 'Assault Rifle (Bullpup)', 'type': 'WEAPONS', 'origin': 'AUSTRIA', 'wiki_title': 'Steyr_AUG', 'desc': 'An Austrian 5.56x45mm NATO bullpup assault rifle.', 'stats': [{'label': 'MODULARITY', 'value': 95, 'text': 'Quick-change barrel'}, {'label': 'OPTICS', 'value': 85, 'text': 'Integrated 1.5x'}]},
    {'id': 'mp5', 'name': 'Heckler & Koch MP5', 'class': 'Submachine Gun', 'type': 'WEAPONS', 'origin': 'GERMANY', 'wiki_title': 'Heckler_%_%26_Koch_MP5', 'desc': 'One of the most widely used submachine guns in the world, adopted by numerous military and LE agencies.', 'stats': [{'label': 'CALIBER', 'value': 30, 'text': '9x19mm Parabellum'}, {'label': 'ACCURACY', 'value': 95, 'text': 'Roller-delayed blowback'}]},
    {'id': 'uzi', 'name': 'Uzi', 'class': 'Submachine Gun', 'type': 'WEAPONS', 'origin': 'ISRAEL', 'wiki_title': 'Uzi', 'desc': 'A family of Israeli open-bolt, blowback-operated submachine guns.', 'stats': [{'label': 'FIRE RATE', 'value': 80, 'text': '600 RPM'}, {'label': 'COMPACTNESS', 'value': 95, 'text': 'Telescoping bolt'}]},
    {'id': 'p90', 'name': 'FN P90', 'class': 'Personal Defense Weapon', 'type': 'WEAPONS', 'origin': 'BELGIUM', 'wiki_title': 'FN_P90', 'desc': 'A compact 5.7x28mm personal defense weapon designed for vehicle crews and special forces.', 'stats': [{'label': 'CAPACITY', 'value': 95, 'text': '50-round mag'}, {'label': 'ARMOR PENETRATION', 'value': 85, 'text': 'SS190 round'}]},
    {'id': 'vector', 'name': 'KRISS Vector', 'class': 'Submachine Gun', 'type': 'WEAPONS', 'origin': 'USA', 'wiki_title': 'KRISS_Vector', 'desc': 'A series of weapons based upon the parent submachine gun design to reduce muzzle climb and felt recoil.', 'stats': [{'label': 'FIRE RATE', 'value': 95, 'text': '1200 RPM'}, {'label': 'RECOIL', 'value': 10, 'text': 'Super V System'}]},
    {'id': 'm249', 'name': 'M249 SAW', 'class': 'Light Machine Gun', 'type': 'WEAPONS', 'origin': 'USA', 'wiki_title': 'M249_light_machine_gun', 'desc': 'The Squad Automatic Weapon provides infantry squads with the heavy volume of fire of a machine gun combined with accuracy and portability.', 'stats': [{'label': 'FIRE RATE', 'value': 85, 'text': '800 RPM'}, {'label': 'CAPACITY', 'value': 90, 'text': '200-round belt'}]},
    {'id': 'pkm', 'name': 'PKM', 'class': 'General-purpose Machine Gun', 'type': 'WEAPONS', 'origin': 'USSR', 'wiki_title': 'PK_machine_gun', 'desc': 'A belt-fed general-purpose machine gun chambered for 7.62x54mmR.', 'stats': [{'label': 'CALIBER', 'value': 85, 'text': '7.62x54mmR'}, {'label': 'RELIABILITY', 'value': 95, 'text': 'Combat Proven'}]},
    {'id': 'm2', 'name': 'M2 Browning', 'class': 'Heavy Machine Gun', 'type': 'WEAPONS', 'origin': 'USA', 'wiki_title': 'M2_Browning', 'desc': 'A heavy machine gun designed towards the end of World War I, still in extensive use today.', 'stats': [{'label': 'CALIBER', 'value': 100, 'text': '.50 BMG (12.7mm)'}, {'label': 'RANGE', 'value': 90, 'text': '1,800 m'}]},
    {'id': 'barrett', 'name': 'Barrett M82', 'class': 'Anti-materiel Rifle', 'type': 'WEAPONS', 'origin': 'USA', 'wiki_title': 'Barrett_M82', 'desc': 'A standardized recoil-operated, semi-automatic anti-materiel sniper system.', 'stats': [{'label': 'CALIBER', 'value': 100, 'text': '.50 BMG'}, {'label': 'RANGE', 'value': 95, 'text': '1,800 m'}]},
    {'id': 'awm', 'name': 'Accuracy International AWM', 'class': 'Sniper Rifle', 'type': 'WEAPONS', 'origin': 'UK', 'wiki_title': 'Accuracy_International_AWM', 'desc': 'A bolt-action sniper rifle manufactured by Accuracy International designed for magnum rifle cartridge chamberings.', 'stats': [{'label': 'CALIBER', 'value': 90, 'text': '.338 Lapua Magnum'}, {'label': 'ACCURACY', 'value': 100, 'text': 'Sub-MOA'}]},
    {'id': 'glock19', 'name': 'Glock 19', 'class': 'Semi-automatic Pistol', 'type': 'WEAPONS', 'origin': 'AUSTRIA', 'wiki_title': 'Glock', 'desc': 'A polymer-framed, short recoil-operated, locked-breech semi-automatic pistol.', 'stats': [{'label': 'CAPACITY', 'value': 70, 'text': '15 rounds (9mm)'}, {'label': 'RELIABILITY', 'value': 95, 'text': 'Safe Action System'}]},
    {'id': 'm1911', 'name': 'M1911', 'class': 'Semi-automatic Pistol', 'type': 'WEAPONS', 'origin': 'USA', 'wiki_title': 'M1911_pistol', 'desc': 'A single-action, semi-automatic, magazine-fed, recoil-operated pistol chambered for the .45 ACP cartridge.', 'stats': [{'label': 'CALIBER', 'value': 80, 'text': '.45 ACP'}, {'label': 'STOPPING POWER', 'value': 85, 'text': 'High'}]},
    {'id': 'sigmcx', 'name': 'SIG MCX', 'class': 'Assault Rifle / PDW', 'type': 'WEAPONS', 'origin': 'USA/GERMANY', 'wiki_title': 'SIG_MCX', 'desc': 'A family of firearms designed and manufactured by SIG Sauer, featuring a short-stroke gas piston system.', 'stats': [{'label': 'MODULARITY', 'value': 100, 'text': 'Multi-caliber'}, {'label': 'SUPPRESSION', 'value': 95, 'text': 'Optimized for .300 BLK'}]}
]

print(f"Starting crawl for {len(raw_data)} assets...")

# Clean up wiki titles (some have % %26 which is a mistake in my dict)
for item in raw_data:
    item['wiki_title'] = item['wiki_title'].replace('%_%26_', '')

final_database = []

def download_file(url, path):
    req = urllib.request.Request(url, headers={'User-Agent': 'RavenX-Tactical-Crawler/2.0'})
    with urllib.request.urlopen(req, timeout=15) as response, open(path, 'wb') as out_file:
        out_file.write(response.read())

for index, item in enumerate(raw_data):
    hw_id = item['id'].lower()
    wiki_title = item['wiki_title']
    filename = f"{hw_id}.jpg"
    filepath = os.path.join(base_dir, filename)
    
    # We will try to get the image
    success = False
    
    if os.path.exists(filepath) and os.path.getsize(filepath) > 1000:
        success = True
        print(f"[{index+1}/{len(raw_data)}] {hw_id} - Exists Locally.")
    else:
        try:
            print(f"[{index+1}/{len(raw_data)}] {hw_id} - Fetching thumbnail from MediaWiki API...")
            api_url = f"https://en.wikipedia.org/w/api.php?action=query&titles={wiki_title}&prop=pageimages&pithumbsize=1000&format=json"
            
            req = urllib.request.Request(api_url, headers={'User-Agent': 'Mozilla/5.0'})
            with urllib.request.urlopen(req, timeout=10) as response:
                data = json.loads(response.read().decode())
                
            pages = data.get('query', {}).get('pages', {})
            page = list(pages.values())[0] if pages else {}
            
            if 'thumbnail' in page:
                img_url = page['thumbnail']['source']
                download_file(img_url, filepath)
                print(f"  -> Downloaded {filename}")
                success = True
            else:
                print(f"  -> No thumbnail found.")
                
            # Sleep 1.5 seconds to avoid rate limiting
            time.sleep(1.5)
            
        except urllib.error.HTTPError as e:
             print(f"  -> HTTP Error: {e.code}")
             time.sleep(5) # Back off on 429
        except Exception as e:
            print(f"  -> Error: {e}")

    if success:
        # Clone item, remove wiki_title, add local image path
        clean_item = dict(item)
        del clean_item['wiki_title']
        clean_item['image'] = f"/hardware/{filename}"
        final_database.append(clean_item)

# Write to JS file
js_content = f"// AUTO-GENERATED DATABASE ({len(final_database)} items)\n\nexport const HARDWARE_DATABASE = "
js_content += json.dumps(final_database, indent=2)
js_content += ";\n"

with open(db_path, 'w', encoding='utf-8') as f:
    f.write(js_content)

print(f"\nCompleted! Successfully wrote {len(final_database)}/{len(raw_data)} items to {db_path}.")
